import { useEffect, useState, type ReactNode } from 'react'
import { ArrowUpRight, Check, ChevronRight, CircleCheck, Dumbbell, Flame, Plus, Send, Target, TrendingDown, Utensils, X, Zap } from 'lucide-react'

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:4000'
type ViewProps = { onBack: () => void; token: string }

async function apiRequest<T>(path: string, token: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...options.headers } })
  const payload = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error((payload as { error?: string }).error || 'Request failed')
  return payload as T
}

export function NutritionView({ onBack, token }: ViewProps) {
  const [mealOpen, setMealOpen] = useState(false)
  const [logged, setLogged] = useState(false)
  const saveMeal = async (meal: { mealName: string; calories: number; proteinGrams: number }) => {
    await apiRequest('/api/nutrition-logs', token, { method: 'POST', body: JSON.stringify(meal) })
    setLogged(true)
    setMealOpen(false)
  }
  return <div className="content-wrap detail-view"><BackLink onBack={onBack} /><div className="view-heading"><div><p className="eyebrow">THURSDAY, SEPTEMBER 11, 2026</p><h1>Nutrition today</h1><p className="subhead">Fuel your training with choices that keep you moving.</p></div><button className="primary-action" onClick={() => setMealOpen(true)}><Plus size={16} /> Log a meal</button></div><div className="nutrition-hero panel"><div className="nutrition-hero-copy"><span className="section-kicker">DAILY TARGET</span><h2>1,240 <small>/ 1,850 kcal</small></h2><p>{logged ? "Nice work. Your lunch is now included in today's total." : '610 calories remaining for today'}</p><div className="large-calorie-track"><i style={{ width: logged ? '78%' : '67%' }} /></div></div><div className="nutrition-hero-stat"><span><Target size={17} /> Goal</span><strong>Fat loss</strong><small>Steady progress</small></div></div><div className="nutrition-view-grid"><section className="panel meal-panel"><div className="panel-heading"><div><span className="section-kicker">TODAY'S LOG</span><h2>Meals & snacks</h2></div><button className="text-button" onClick={() => setMealOpen(true)}><Plus size={15} /> Add meal</button></div><MealRow name="Breakfast" detail="Greek yogurt, berries & oats" calories="360 kcal" done /><MealRow name="Lunch" detail={logged ? 'Chicken bowl with greens & rice' : 'Nothing logged yet'} calories={logged ? '520 kcal' : '—'} done={logged} /><MealRow name="Snack" detail="Add something when you need it" calories="—" /><MealRow name="Dinner" detail="Planned for 7:30 PM" calories="—" /></section><section className="panel macro-panel"><div className="panel-heading"><div><span className="section-kicker">MACROS</span><h2>Balance today</h2></div><Utensils size={18} className="muted-icon" /></div><MacroBar label="Protein" value="94g" target="140g" color="protein" percent={67} /><MacroBar label="Carbohydrates" value="128g" target="210g" color="carbs" percent={61} /><MacroBar label="Fats" value="38g" target="62g" color="fats" percent={61} /><div className="nutrition-tip"><Zap size={16} /><span><strong>Coach tip</strong> A protein-rich snack this afternoon can help you reach your target without a heavy dinner.</span></div></section></div>{mealOpen && <MealModal onClose={() => setMealOpen(false)} onSave={saveMeal} />}</div>
}

export function ProgressView({ onBack, token }: ViewProps) {
  const [range, setRange] = useState('30 days')
  const [summary, setSummary] = useState({ weight: '74.2', workoutsThisWeek: 14 })
  useEffect(() => { void apiRequest<{ summary: { weight: string | number; workoutsThisWeek: number } }>('/api/progress/summary', token).then(({ summary: next }) => setSummary({ weight: String(next.weight), workoutsThisWeek: next.workoutsThisWeek })).catch(() => undefined) }, [token])
  return <div className="content-wrap detail-view"><BackLink onBack={onBack} /><div className="view-heading"><div><p className="eyebrow">YOUR JOURNEY</p><h1>Progress that adds up</h1><p className="subhead">Consistency is showing. Keep building on your wins.</p></div><div className="range-tabs">{['7 days', '30 days', '3 months'].map((item) => <button key={item} className={range === item ? 'active' : ''} onClick={() => setRange(item)}>{item}</button>)}</div></div><div className="progress-metrics"><Metric label="Weight" value={`${summary.weight} kg`} detail="Latest check-in" /><Metric label="Workouts" value={String(summary.workoutsThisWeek)} detail="This week" /><Metric label="Consistency" value="86%" detail="↑ 12% this month" /><Metric label="Best streak" value="18 days" detail="Personal best" /></div><div className="progress-view-grid"><section className="panel large-chart-panel"><div className="panel-heading"><div><span className="section-kicker">BODY WEIGHT</span><h2>Trend over {range}</h2></div><button className="more-button" aria-label="More chart options"><ChevronRight size={18} /></button></div><div className="large-chart"><div className="large-chart-labels"><span>78</span><span>76</span><span>74</span><span>72</span></div><svg viewBox="0 0 700 220" preserveAspectRatio="none" role="img" aria-label="Weight trend chart"><path className="large-area" d="M0,38 C55,48 70,30 120,62 S190,50 240,80 S305,58 350,100 S420,76 460,112 S535,98 580,150 S650,121 700,145 L700,220 L0,220 Z" /><path className="large-line" d="M0,38 C55,48 70,30 120,62 S190,50 240,80 S305,58 350,100 S420,76 460,112 S535,98 580,150 S650,121 700,145" /><circle cx="580" cy="150" r="6" className="large-point" /></svg></div><div className="chart-dates"><span>Aug 12</span><span>Aug 22</span><span>Sep 1</span><span>Sep 11</span></div></section><section className="panel milestones-panel"><div className="panel-heading"><div><span className="section-kicker">MILESTONES</span><h2>Recent wins</h2></div><Target size={18} className="muted-icon" /></div><Milestone icon={<Flame size={16} />} title="12 day streak" detail="You're building a rhythm" /><Milestone icon={<Dumbbell size={16} />} title="14 workouts completed" detail="3 more than last month" /><Milestone icon={<TrendingDown size={16} />} title="First 2 kg milestone" detail="Reached September 2" /></section></div></div>
}

export function CoachView({ onBack, onSendMessage, token }: ViewProps & { onSendMessage?: (message: string) => Promise<string> | string }) {
  const [message, setMessage] = useState('')
  const [messages, setMessages] = useState([{ from: 'coach', text: "Good morning, Jordan. You're on a strong rhythm this week. How can I help today?" }])
  const sendMessage = async () => { if (!message.trim()) return; const nextMessage = message.trim(); setMessages((items) => [...items, { from: 'user', text: nextMessage }]); setMessage(''); try { const response = onSendMessage ? await onSendMessage(nextMessage) : (await apiRequest<{ message: string }>('/api/coach/messages', token, { method: 'POST', body: JSON.stringify({ message: nextMessage }) })).message; setMessages((items) => [...items, { from: 'coach', text: response }]) } catch { setMessages((items) => [...items, { from: 'coach', text: 'I hear you. I can adjust today\'s plan around that. Your progress matters more than a perfect day.' }]) } }
  return <div className="content-wrap detail-view"><BackLink onBack={onBack} /><div className="view-heading coach-view-heading"><div><p className="eyebrow">COACH NOVA · ONLINE</p><h1>A little support, right when you need it.</h1><p className="subhead">Ask about your plan, swap an exercise, or check in with how you feel.</p></div><div className="coach-status"><span className="status-dot" /> Ready to help</div></div><div className="chat-layout"><section className="panel chat-panel"><div className="chat-messages">{messages.map((item, index) => <div className={`chat-bubble ${item.from}`} key={`${item.from}-${index}`}><span>{item.from === 'coach' ? 'CN' : 'JD'}</span><p>{item.text}</p></div>)}</div><div className="chat-prompts"><button onClick={() => setMessage("I'm feeling tired today")}>I'm feeling tired</button><button onClick={() => setMessage('Can we swap an exercise?')}>Swap an exercise</button><button onClick={() => setMessage('What should I eat after training?')}>Post-workout food</button></div><div className="chat-composer"><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void sendMessage()} placeholder="Message your coach..." /><button onClick={() => void sendMessage()} aria-label="Send message"><Send size={17} /></button></div></section><aside className="panel coach-context"><span className="section-kicker">YOUR CONTEXT</span><h2>What Nova knows</h2><div><Target size={16} /><span>Goal<strong>Fat loss</strong></span></div><div><Flame size={16} /><span>Current streak<strong>12 days</strong></span></div><div><Dumbbell size={16} /><span>Today's focus<strong>Lower body strength</strong></span></div><p>Coach guidance is for fitness support, not medical advice.</p></aside></div></div>
}

export function SettingsView({ onBack, token, darkMode, onToggleDark }: ViewProps & { darkMode: boolean; onToggleDark: () => void }) {
  const [reminders, setReminders] = useState({ enabled: true, reminderTime: '07:30', reminderDays: [1, 2, 3, 4, 5] })
  useEffect(() => { void apiRequest<{ preferences: typeof reminders }>('/api/notification-preferences', token).then(({ preferences }) => setReminders(preferences)).catch(() => undefined) }, [token])
  const toggleReminders = async () => { const next = { ...reminders, enabled: !reminders.enabled }; setReminders(next); await apiRequest('/api/notification-preferences', token, { method: 'PUT', body: JSON.stringify(next) }) }
  return <div className="content-wrap detail-view"><BackLink onBack={onBack} /><div className="view-heading"><div><p className="eyebrow">YOUR SPACE</p><h1>Settings</h1><p className="subhead">Shape FitPulseAI around the way you live.</p></div></div><div className="settings-layout"><section className="panel settings-panel"><SettingRow title="Appearance" detail={darkMode ? 'Dark mode is on' : 'Light mode is on'} icon={darkMode ? '☾' : '☀'} action={<button className="setting-switch" onClick={onToggleDark}><i className={darkMode ? 'on' : ''} /></button>} /><SettingRow title="Workout reminders" detail={reminders.enabled ? `Weekdays at ${reminders.reminderTime}` : 'Reminders are off'} icon="◷" action={<button className="setting-switch" onClick={() => void toggleReminders}><i className={reminders.enabled ? 'on' : ''} /></button>} /><SettingRow title="Units" detail="Kilograms · Metric" icon="⌁" action={<button className="setting-link">Edit</button>} /><SettingRow title="Privacy & data" detail="Manage your information and consent" icon="◇" action={<ChevronRight size={17} />} /></section><section className="panel settings-profile"><div className="avatar">JD</div><h2>Jordan Davis</h2><p>Fat loss journey · Started August 12, 2026</p><button className="text-button">Edit profile <ArrowUpRight size={15} /></button></section></div></div>
}

function BackLink({ onBack }: { onBack: () => void }) { return <button className="back-button" onClick={onBack}><ChevronRight size={16} className="back-arrow" /> Back to overview</button> }
function MealRow({ name, detail, calories, done }: { name: string; detail: string; calories: string; done?: boolean }) { return <div className="meal-row"><span className={`meal-status ${done ? 'done' : ''}`}>{done && <Check size={13} />}</span><div><strong>{name}</strong><span>{detail}</span></div><b>{calories}</b><ChevronRight size={15} className="muted-icon" /></div> }
function MacroBar({ label, value, target, color, percent }: { label: string; value: string; target: string; color: string; percent: number }) { return <div className="macro-bar"><div><span><i className={`macro-dot ${color}`} />{label}</span><strong>{value} <small>/ {target}</small></strong></div><div className="macro-track"><i className={color} style={{ width: `${percent}%` }} /></div></div> }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="metric-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
function Milestone({ icon, title, detail }: { icon: ReactNode; title: string; detail: string }) { return <div className="milestone"><span>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><CircleCheck size={16} /></div> }
function MealModal({ onClose, onSave }: { onClose: () => void; onSave: (meal: { mealName: string; calories: number; proteinGrams: number }) => Promise<void> }) { const [mealName, setMealName] = useState('Chicken bowl with greens & rice'); const [calories, setCalories] = useState('520'); const [protein, setProtein] = useState('38'); return <div className="modal-backdrop" onClick={onClose}><div className="modal-card" onClick={(event) => event.stopPropagation()}><div className="modal-heading"><div><span className="section-kicker">QUICK LOG</span><h2>Add a meal</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18} /></button></div><label>Meal name<input value={mealName} onChange={(event) => setMealName(event.target.value)} /></label><div className="modal-fields"><label>Calories<input value={calories} onChange={(event) => setCalories(event.target.value)} type="number" /></label><label>Protein<input value={protein} onChange={(event) => setProtein(event.target.value)} /></label></div><button className="primary-action modal-save" onClick={() => void onSave({ mealName, calories: Number(calories) || 0, proteinGrams: Number.parseFloat(protein) || 0 })}><Check size={16} /> Save meal</button></div></div> }
function SettingRow({ title, detail, icon, action }: { title: string; detail: string; icon: string; action: ReactNode }) { return <div className="setting-row"><span className="setting-icon">{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><span className="setting-action">{action}</span></div> }
